/**
 * scripts/fetch-branding.ts
 *
 * Downloads the Gravitas logo SVG from the canonical source URL, validates it,
 * base64-encodes it, and rewrites src/lib/branding/logo.ts with the embedded
 * data URI.
 *
 * Run:    pnpm branding:fetch
 *
 * Why: docs/BRANDING.md — "Logo" → every visitor-facing artifact (canvas,
 * audit report, lead form, daily-cap card, PDF) imports
 * GRAVITAS_LOGO_DATA_URI. No runtime fetch from assets.thisisgravitas.com:
 * runtime fetches can fail (asset host down, PDF generator in a network-less
 * sandbox), and the trade-off — a slightly larger bundle + a manual refresh
 * on logo changes — is acceptable.
 *
 * Idempotent: re-run any time the logo changes. The generated file is
 * committed; CI does not run this on every build.
 */

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const SOURCE_URL =
  "https://assets.thisisgravitas.com/Gravitas_Wordmark_White_e7585d98d5.svg";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(HERE, "..", "src", "lib", "branding", "logo.ts");

async function main(): Promise<void> {
  log("fetching", SOURCE_URL);
  const res = await fetch(SOURCE_URL, {
    headers: { Accept: "image/svg+xml" },
  });
  if (!res.ok) {
    fatal(`fetch returned ${res.status} ${res.statusText}`);
  }
  const svg = await res.text();

  // Cheap sanity gate — we expect an SVG, not an HTML 404 page that happens
  // to have status 200 (looking at you, generic CDNs).
  const trimmed = svg.trimStart();
  if (!trimmed.startsWith("<svg") && !trimmed.startsWith("<?xml")) {
    fatal(
      "response is not an SVG document (no <svg or <?xml prefix). " +
        "Check the source URL hasn't moved.",
    );
  }
  if (svg.length > 256 * 1024) {
    fatal(`response is ${svg.length} bytes — refusing to embed >256KB`);
  }

  const base64 = Buffer.from(svg, "utf8").toString("base64");
  const dataUri = `data:image/svg+xml;base64,${base64}`;

  const fileContent = renderLogoModule({
    sourceUrl: SOURCE_URL,
    dataUri,
    bytes: svg.length,
  });

  await writeFile(OUTPUT_PATH, fileContent, "utf8");
  log("wrote", OUTPUT_PATH, `(${svg.length} bytes svg → ${base64.length} bytes base64)`);
}

function renderLogoModule(opts: {
  sourceUrl: string;
  dataUri: string;
  bytes: number;
}): string {
  return (
    "/**\n" +
    " * Gravitas logo — embedded asset.\n" +
    " *\n" +
    " * Generated by `pnpm branding:fetch`. Do NOT edit by hand.\n" +
    " * Run the script again to refresh from the canonical source URL.\n" +
    " *\n" +
    " * Rule (docs/BRANDING.md): every visitor-facing surface imports\n" +
    " * GRAVITAS_LOGO_DATA_URI. No runtime fetch from assets.thisisgravitas.com.\n" +
    " */\n" +
    "\n" +
    `export const GRAVITAS_LOGO_SOURCE_URL = ${JSON.stringify(opts.sourceUrl)};\n` +
    "\n" +
    `/** Original SVG was ${opts.bytes} bytes; embedded as base64 below. */\n` +
    `export const GRAVITAS_LOGO_DATA_URI: string = ${JSON.stringify(opts.dataUri)};\n` +
    "\n" +
    "/**\n" +
    " * Indicates the logo currently in the bundle is the real Gravitas-hosted SVG\n" +
    " * (vs the inline fallback shipped with the scaffold).\n" +
    " */\n" +
    "export const GRAVITAS_LOGO_IS_REAL: boolean = true;\n"
  );
}

function log(...args: unknown[]): void {
  // eslint-disable-next-line no-console
  console.log("[branding:fetch]", ...args);
}

function fatal(message: string): never {
  // eslint-disable-next-line no-console
  console.error("[branding:fetch] FAILED —", message);
  process.exit(1);
}

void main().catch((err: unknown) => {
  fatal(err instanceof Error ? err.message : String(err));
});
